# Generated by Django 2.2.18 on 2021-05-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=32, verbose_name='厂家名称')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('flavor', models.CharField(max_length=32, verbose_name='口味')),
                ('date_of_manufacture', models.DateField(verbose_name='生产日期')),
                ('shelf_data', models.IntegerField(default=24, verbose_name='保质期')),
                ('now_time', models.CharField(max_length=32, verbose_name='当前时间')),
                ('overdue', models.IntegerField(default=0, verbose_name='过期天数')),
                ('is_put', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_sell', models.BooleanField(default=False, verbose_name='是否出售')),
                ('brand', models.ForeignKey(on_delete=True, to='web.Brand', verbose_name='品牌')),
            ],
        ),
    ]
